version: "3.4"
services:
  api-gateway:
    image: xdima/api-gateway
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - hello_net

  customer:
    image: xdima/customer
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - hello_net

  owner:
    image: xdima/owner
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - hello_net

  zipkin:
    image: openzipkin/zipkin
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "9411:9411"
    networks:
      - hello_net
    environment:
      # Set to false to disable creation of spans via HTTP collector API
      - HTTP_COLLECTOR_ENABLED=false
      # ZooKeeper host string, comma-separated host:port value.
      - KAFKA_ZOOKEEPER=10.136.2.69:2181
      # Name of topic to poll for spans
      - KAFKA_TOPIC=zipkin
      # Consumer group this process is consuming on behalf of.
      - KAFKA_GROUP_ID=zipkin
      # Percentage of traces to retain, defaults to always sample (1.0).
      #- COLLECTOR_SAMPLE_RATE=0.5
networks:
  hello_net: